### ISSUE TITLE
"Actions must be plain objects." error

### ISSUE THREAD

**Issue by munik** [cartant/ts-action#1]
I really like the ts-action library. It would significantly reduce our Redux action boilerplate.

I've gotten the ES6 polyfills working, but now I'm running into this error when I try to dispatch a ts-action class on the Redux store:

`Actions must be plain objects. Use custom middleware for async actions.`

What middleware do you use to get this to work?

**Comment by cartant** [comment]
Thanks for raising the issue. I'd forgotten that React enforced that. This should be fixed in 2.0.2 via https://github.com/cartant/ts-action/commit/9925f79011d0e64544dc922fcbf97739bc6cf216
