### ISSUE TITLE
how to use action with effects?

### ISSUE THREAD

**Issue by maku** [cartant/ts-action#12]
Can you provide a full example (with imports) how to use an action with effects. 

e.g.

in a naive approach I would write the following.

```
import { Injectable } from '@angular/core';
import { Actions, Effect } from '@ngrx/effects';
import { LoginAction } from './auth.actions';
import { tap } from 'rxjs/operators';
import { action, payload } from 'ts-action';

// Action
export const LoginAction = action('[Auth] LOGIN', payload<LoginDto>());

// Effects
@Injectable()
export class AuthEffects {

  private constructor(private actions$: Actions) {
  }

  @Effect({dispatch: false})
  login$ = this.actions$.ofType(LoginAction.type).pipe(
    tap((action: LoginAction) => {
      console.log('login action', action.payload);
    })
  );

}


```

But the compiler complains about LoginAction in the pipe function (of course)

Can you help, please??

**Comment by cartant** [comment]
You need to use the pipeable `ofType` operator that's in `ts-action-operators`:

```ts
import { Injectable } from '@angular/core';
import { Actions, Effect } from '@ngrx/effects';
import { LoginAction } from './auth.actions';
import { tap } from 'rxjs/operators';
import { action, payload } from 'ts-action';
import { ofType } from 'ts-action-operators';

// Action
export const LoginAction = action('[Auth] LOGIN', payload<LoginDto>());

// Effects
@Injectable()
export class AuthEffects {

  private constructor(private actions$: Actions) {
  }

  @Effect({dispatch: false})
  login$ = this.actions$.pipe(
    ofType(LoginAction),
    tap((action: LoginAction) => {
      console.log('login action', action.payload);
    })
  );

}
```

**Comment by cartant** [comment]
`ts-action-operators` is mentioned in the [README](https://github.com/cartant/ts-action#why-might-you-need-it), but I will try to make this clearer.

**Comment by cartant** [comment]
I've updated the README to make this clearer.

**Comment by maku** [comment]
@cartant thank you for your support. BUT the typescript compiler (v2.6.2) still flag an error (TS2304 "Cannnot find name 'LoginAction') for the usage of LoginAction as parameter type for 'tap'

**Comment by cartant** [comment]
I see. `LoginAction` is not a type. It's a constructor - note that it's a `const` that's assigned to, so it cannot be used as a type. If you are using `ofType` from `ts-action-operators`, there is no need to specify the type, as it will be inferred correctly. That is, the type of the `action` parameter will be known; it will be based on the type of the observable returned by `ofType`

I would strongly recommend not specifying types in arrow functions unless they are required:

```ts
tap((action: LoginAction) => {
  console.log('login action', action.payload);
 })
```

TypeScript type inferences are a feature I would recommend using.

If you absolutely, positively must type all that stuff in, with version 6.0.0 the actual action type is accessible via a static property of the constructor:

```ts
tap((action: typeof LoginAction,action) => {
  console.log('login action', action.payload);
 })
```

But, again, I would recommend that you not do this. I built the package to cut down on boilerplate code.

**Comment by maku** [comment]
@cartant ok great. Usually I prefer to specify the type to make the code as readable as possible. But in this case, of course the "ofType(LoginAction)" makes the type of "action" very clear.

Thank you for the support. I really like the library because of reducing the boilerplate.

**Comment by cartant** [comment]
No worries. It is initially a little confusing that the constructor is not the type, as they usually share the same name. However, it's not possible here, as the constructors/classes are not declared statically - they are created at runtime.
