### ISSUE TITLE
Question: why is ts-action installed as a dev-dependency

### ISSUE THREAD

**Issue by st-clair-clarke** [cartant/ts-action#13]
Hi,
In the docs I see the instruction for installation as 
`npm install ts-action --save-dev`

Why is this so?
Should the same be done with ts-action-action-operators too?

Cheers

**Comment by cartant** [comment]
I guess it's an error. Copy/paste errors are my speciality.

It most like came from my copying it from the `README.md` that's in `firebase-nightlight` - which is a testing tool.

You are right. It should be `--save` not `--save-dev` here. Thanks. I'll update the docs.

**Comment by cartant** [comment]
I've updated the docs. Thanks.

**Comment by st-clair-clarke** [comment]
Great! And thanks.
