### ISSUE TITLE
ts-action library requires polyfill on React Native Android

### ISSUE THREAD

**Issue by lnhrdt** [cartant/ts-action#15]
I'm building a react-native app and using your ts-action library. Thanks, it's neat.

I've noticed that instantiating an action (calling the constructor on an ActionCtor type) throws an error on Android. I get `undefined is not a function (evaluating 'Object.setPrototypeOf(_this, literalPrototype)')`. On iOS the code works fine.

Also, adding a polyfill for setPrototypeOf to my application (like [MDN's polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setprototypeof#Polyfill)) fixes the problem.

I'm not sure the best way to address this, or if it's even the responsibility of this library to care about usage on react-native Android, but thought I'd report it and start a discussion.

**Comment by cartant** [comment]
Thanks for raising the issue. The polyfill is so simple that I think the best solution is to include it in the library as a [ponyfill](https://github.com/sindresorhus/ponyfill). I'll add it to my list of things to do.

**Comment by cartant** [comment]
[This](https://github.com/wesleytodd/setprototypeof) oughta do it.

**Comment by lnhrdt** [comment]
Thanks for link explaining the difference between ponyfill and polyfill! I never knew the difference until now.

> This oughta do it.

If you use `wesleytodd/setprototypeof` as a ponyfill instead of relying on `Object.setPrototypeOf` in your library then yes, that would solve the problem!

**Comment by cartant** [comment]
This should be fixed in 6.0.2 which has just been published. The MDN polyfill is now included (as a ponyfill).

**Comment by lnhrdt** [comment]
Confirming that 6.0.2 doesn't require a polyfill anymore on Android and it's fixed. Thanks for the fast response!
