### ISSUE TITLE
How to pass few actions in reducer on() method

### ISSUE THREAD

**Issue by thekip** [cartant/ts-action#24]
In "classic" redux pattern, switch is used for handling actions in reducer. 
One of the "benefits" of using switches, it allows creating "fall-through" statements, eq: 

```js
const reducer = (state = initialState, action) => {
  switch (action.type) {
    case TYPE_A:
    case TYPE_B: {
      //.. do something fro both actions
    }
  }
};
```

But unfortunately it isn't possible to do using `reducer()` / `on()`  functions from this library. 

This is quite inconvinient, because some redux practicies rely on this feature. And for now it cause additional boilerplate.

**Comment by cartant** [comment]
At the moment, you'd have to do something like this:

```ts
const FooBar = union({ Foo, Bar });
const r = (state, action: typeof FooBar) => /* ... */;
const fooBarReducer = reducer<State>([
    on(Foo, r),
    on(Bar, r)
], {});
```

Which is pretty horrid.

However, it would be straightforward to allow a map of actions to be passed to `on` - as is done with `union` - like this:

```ts
const fooBarReducer = reducer<State>([
    on({ Foo, Bar }, (state, action) => /* ... */),
], {});
```

**Comment by cartant** [comment]
This is implemented, now. See [this test](https://github.com/cartant/ts-action/blob/master/source/reducer-spec.ts#L73-L91). I'll publish a new version of the package tomorrow. In the interim, if you want to play with it, just clone the repo.

**Comment by cartant** [comment]
7.0.0 has just been published.
