### ISSUE TITLE
Support `on` with multiple actions as array

### ISSUE THREAD

**Issue by bekos** [cartant/ts-action#27]
Can you support something like this:
```
on([ Bar, Foo ], (state, { type }) => [...state, type])
```
Thx 👍

**Comment by cartant** [comment]
Why?

**Comment by cartant** [comment]
> Maybe you need to update README

I guess so. :smile:

Supporting multiple actions in `on` is something I added only in the last few days.

**Comment by liucougar** [comment]
May I ask why supporting array is impossible please? is it related to ReturnType() can't accept an array element as argument?

**Comment by cartant** [comment]
It didn't say it was impossible. I said I didn't *think is was possible*. The reason being is that I am not aware of a tuple equivalent to the mapped types that work with objects.

**Comment by cartant** [comment]
Actually, looking at this again, I think I'm wrong and that arrays could also be supported. I'll look more closely at this later and will add support if it's possible.

**Comment by cartant** [comment]
Done in 8.1.0.
