### ISSUE TITLE
Updated action

### ISSUE THREAD

**Issue by will-stone** [cartant/ts-action#28]
Hi Nicholas.

This isn't an issue; just a discussion, carrying on from the issue I raised the other day (#26).

I found this website: https://qiita.com/terrierscript/items/b9687f610a96ab964ab2 and although I can't understand the text, I have managed to build upon the code. Here is the current solution that we quite like for our actions and I was hoping it might help you with your refactor.

```ts
import { Action } from 'redux'

type TPayloadFn<Args extends any[], R> = (...args: Args) => R
type TActionCreator<Args extends any[], A> = (...args: Args) => A

type TAction<T extends string, Payloads extends {} = {}> = Action<T> &
  { [K in keyof Payloads]: Payloads[K] }

function a<T extends string>(
  type: T,
): { TYPE: T; create: TActionCreator<any[], TAction<T>> }
function a<T extends string, Args extends any[], R>(
  type: T,
  fn: TPayloadFn<Args, R>,
): { TYPE: T; create: TActionCreator<Args, TAction<T, R>> }
function a(type: string, payloadFn?: any) {
  return {
    TYPE: type,
    create: (...args: any[]) => {
      if (payloadFn) {
        const extra = payloadFn(...args)
        return { type, ...extra }
      }
      return { type }
    },
  }
}
```

This allows us to write our current actions...
```ts
export class ATestAction {
  public static readonly TYPE = 'TEST/ACTION'
  public static create(str: ATestAction['str']): ATestAction {
    return { type: ATestAction.TYPE, str }
  }
  public readonly type = ATestAction.TYPE
  public readonly str: string
}
```
as...
```ts
export const ATestAction = a('TEST/ACTION', (str: string) => ({ str }))
export type ATestAction = ReturnType<typeof ATestAction.create>
```

This allows us to get the redux type of the action with:
```ts
ATestAction.TYPE
```
Create a new action with:
```ts
ATestAction.create('some string')
/* Producing:
{
  type: 'TEST/ACTION',
  str: 'some string'
}
*/
```
And the TS type of the action with just:
```ts
ATestAction
```
(which was based on your suggestion from that other issue, thanks).

Now, I'd quite like to get the payloadFn even smaller, maybe even the same way you do:
```ts
export const ATestAction = a('TEST/ACTION', p<{str: string}>())
export type ATestAction = ReturnType<typeof ATestAction.create>
```

If you have found this helpful, I'd really appreciate it if you could take a look at how I'd achieve that.

**Comment by cartant** [comment]
The part that makes the `payload<{ value: number }>())` bit work in [this line](https://github.com/cartant/ts-action/blob/v7.0.0/source/action.ts#L24).

The `payload` and `base` functions, etc. return a specific type from which the properties, parameters or base is inferred. At the moment, I cannot think of another way of explaining it. I think you'll just need to read the code until it clicks.

BTW, that implementation in your comment is pretty similar to the re-implementation that I mentioned - in which I intend to replace the classes with simple functions. However, I'm not intending on putting `create` function inside something; I was going to have `action` just return the action creator function itself.

**Comment by will-stone** [comment]
Thanks. That's cool, I think I'm getting there slowly. I was just hoping to have a payload (or in your words: "props") function that worked with my implementation; I'm sure I'll figure it out eventually.

Do you mean yours will do this?
```ts
ATestAction('some string')

/* Producing:
{
  type: 'TEST/ACTION',
  str: 'some string'
}
*/
```

I wrapped ours so that we had easy access to `TYPE` and would mean no code changes for us. Is it possible to have `ATestAction('some string')` create the action and `ATestAction.type` return the redux type?

**Comment by cartant** [comment]
IIRC, it should be like this:

```ts
const foo = action("FOO", props<{ message: string }>());
type Foo = ReturnType<typeof foo>;
dispatch(foo("Hey, you!"));
```

Which would dispatch this:

```json
{
  "message": "Hey, you!",
  "type": "FOO"
}
```

**Comment by will-stone** [comment]
Ah, yes. Sorry, I meant the Action constant. Would you simply expect those to be exported separately?

```ts
export const FOO = 'FOO'
export const foo = action(FOO, props<{ message: string }>());
export type Foo = ReturnType<typeof foo>; // If you need it anywhere.
```

The idea behind my wrapper was to keep it down to 2 exports, and one import, i.e. I only need import `ATestAction` to obtain access to the redux action type, the redux action creator, and the ts type.

No worries if we're heading in two different directions. Thanks for all your help (and very quick responses!).

**Comment by cartant** [comment]
The type constant would be available, as it has is now, via a `type` property on the action creator function: `foo.type`.

The `action` property will probably be there, too. Although, with more recent versions of TypeScript, it's likely unnecessary (the lib was written to work with 2.6, IIRC).

The main reason for the change would be to remove the creation of class instances instead of plain objects, as creating instances necessitates clobbering the prototype for it to work with Redux.

**Comment by will-stone** [comment]
Hi @cartant, just to let you know, we released our version, it's called 'a': https://github.com/ArtosSystems/a It's the first public version but has gone through 3 iterations until we landed on the current implementation. You are of course credited for all the help you provided me, thank-you.
