### ISSUE TITLE
Use a rest parameter for multiple actions

### ISSUE THREAD

**Issue by cartant** [cartant/ts-action#32]
Refactor `union`, et al. to:

* use a rest parameter for multiple actions;
* deprecate multiple actions expressed as an array literal;
* remove support for multiple actions expressed as an object literal; and
* remove support for class-based actions.

**Comment by liucougar** [comment]
so instead of `union([foo,bar])`, we can do `union(foo, bar)`?

**Comment by cartant** [comment]
Yeah. It's almost done. `on` is the only tricky one. See the `rest` branch.

**Comment by cartant** [comment]
v9.0.0 now does away with array and object literal representations of multiple actions and uses multiple parameters instead.
