### ISSUE TITLE
Support Immer

### ISSUE THREAD

**Issue by potty** [cartant/ts-action#37]
Hi, do you plan to support Immer (https://github.com/immerjs/immer) in reducer function?

**Comment by cartant** [comment]
What's stopping you from using it?

**Comment by potty** [comment]
Sure I can use it on my own, but I mean some direct implementation in ts-action reducer function, something like redux-starter-kit is using (https://github.com/reduxjs/redux-starter-kit/blob/master/src/createReducer.ts).

**Comment by cartant** [comment]
I don't want to add it to `ts-action`, but I think having an alternative, Immer-based `reducer` in, say, `ts-action-immer` would be worthwhile. I'm looking into it, ATM. I've just re-arranged `ts-action` and `ts-action-operators` into a monorepo. Adding `ts-action-immer` should be pretty easy.

**Comment by cartant** [comment]
Have a look at `ts-action-immer` - which has just been published - and the [README](https://github.com/cartant/ts-action/blob/master/packages/ts-action-immer/README.md).
