### ISSUE TITLE
Immer: Access reducer state

### ISSUE THREAD

**Issue by daarxwalker** [cartant/ts-action#43]
Hi,
if I want to access reducer state in on method, which is in immer produce first arg, is there any way? For example: I want to compare array values in reducer, and if they are same, merged them, but now I can't, because in immer way ts-action-immer on method dunno how to access reducer state. There is a way to pass list as payload, but it's really not necessary, or use classic on method, not immer. So my question is, why I can't access reducer state, but only draft, original immer can do this.
Thanks for the answer!

**Comment by cartant** [comment]
I don't understand the question. My understanding is that the draft is a proxy for the state, so anything that can be read from the state can be read from the draft.

**Comment by daarxwalker** [comment]
You're right! I was confused, when I didn't see state in console, just only proxy. Cool!
Sorry for misunderstanging! Keep it good work!

**Comment by cartant** [comment]
No worries.
