### ISSUE TITLE
Array type inference

### ISSUE THREAD

**Issue by potty** [cartant/ts-action#47]
Hi, after the latest update of ts-actions and ts-actions-immer, type inference of array is somewhat strange. I have initial state:

```ts
const initialState = {
  list: [] as Product[],
}
```

This list is inferred as never[] in state arg in `on()` function.

```ts
on(someAction, state => {
  // state.list is never[] here
  state.list = state.list.map(item => ({ ...item, isNew: false }))
}),
```

**Comment by cartant** [comment]
I would need more information, as I can't reproduce this behaviour by adding a test withing `ts-action-immer`:

```ts
it("temp", () => {
  type Product = { name: string; };
  const initialState = {
    list: [] as Product[]
  };
  const r = reducer(
    initialState,
    on(foo, (state, { foo }) => ({ ...state, foo })),
    on(bar, state => { state.list = [...state.list]; })
  );
});
```

Here, in both of the `on` calls, the `state` parameters is inferred to be:

```ts
state: {
    list: {
        name: string;
    }[];
}
```

**Comment by potty** [comment]
Well, I found out I was using Immer version 1 thanks to some other dependency, so the newest version was not installed. Now with version 4 it works fine. Closing this.
