### ISSUE TITLE
Bug: ofType doesn't work

### ISSUE THREAD

**Issue by Bielik20** [cartant/ts-action#48]
Versions:
- ts-action@11.0.0
- ts-action-operators@9.1.1

I have a scenario:

```ts
import { action, props } from 'ts-action';
import { ofType } from 'ts-action-operators';

export const authorized = action(
  '[Auth Epic] authorized',
  props<{ user: User; token: string }>(),
);

const authorizedEpic = (action$, state$) =>
  action$.pipe(
    ofType(authorized),
    distinctUntilChanged((a, b) => a.token === b.token),
    ...
  );
```

Complier complains: `Property 'token' does not exist on type '{}'.`.

I have previously worked with NgRx and had no issues like that. Is there something I am doing wrong or is `ofType` operator broken?

**Comment by cartant** [comment]
This isn't a bug. The root of your problem is this line:

```ts
const authorizedEpic = (action$, state$) =>
```

There is no way for TypeScript to know what the types of `action$` and `state$` are.

**Comment by Bielik20** [comment]
I perhaps put it wrong. It is not the ofType operator that makes problems.
It is the distinctUntilChanged one. Sorry for not providing this
information upfront.

The problem is that I would expect distinctUntilChanged operator to know
the type of its input but it doesn't.

W dniu niedz., 17.11.2019 o 12:40 Nicholas Jamieson <
notifications@github.com> napisał(a):

**Comment by cartant** [comment]
The inference doesn't work for the reason that I highlighted. In your snippet, `action$` has the type `any` and that is the root of the problem.

**Comment by Bielik20** [comment]
I am very surprised but now it works, thank you. And here I thought I understand typescript.

`actions$` is `any`, which is fine, but the operator definition is:

```ts
function ofType<C extends ActionCreator[]>(...creators: C): (source: Observable<Action>) => Observable<ActionType<C[number]>>
```

So it still should map stream to appropriate action. I guess it is because type of `source` (`actions$`) as `any` is not narrow enough... but `source` as `Observable<any>` works. Sorry for trouble I will try to figure out myself why it didn't "click".

Thank you for our help.

**Comment by cartant** [comment]
The inference fails because `pipe` is called on `any` - not on `Observable` - so it cannot match the `pipe` method on observable. That means there is no relationship between the arguments passed to `pipe`, so the output of `ofType` has no affect on `distinctUntilChanged`. When `action$` is typed correctly, a `pipe` signature is matched and the inference flows as you'd expect it to.

**Comment by Bielik20** [comment]
Ok, I did not consider the problem was on the pipe level, thanks :)
