### ISSUE TITLE
Immer v6

### ISSUE THREAD

**Issue by potty** [cartant/ts-action#50]
Hi, can you release a version supporting the new Immer v6, please?

**Comment by cartant** [comment]
Have you verified whether it's just a peer warning or whether there are breaking changes that affect this lib?

**Comment by potty** [comment]
AFAIK from my experience only peer warnings, been using it for a while without issues.

**Comment by cartant** [comment]
No worries. I'll bump the dev version, widen the peer version and if the tests pass I'll publish it right away.

**Comment by cartant** [comment]
Done. 3.0.2 should be available.
