### ISSUE TITLE
Question: how to get action type definition (usecase: redux-saga)

### ISSUE THREAD

**Issue by aarjithn** [cartant/ts-action#53]
Hello,

Suppose we have defined an action like this

```
export const setLoading = action(
  '[app] SET_LOADING',
  payload<boolean>(),
);
```

In redux saga, we assign a generator function against an action, and the generator function gets action object passed on to it.

```
yield takeLatest(setLoading.type, onSetLoading); // when this action is found, call generator fn

function* onSetLoading(action: <type of action object>) // In this case, its `{ type: '[app] SET_LOADING', payload: boolean }`
```

Have found below solution which seem to work, but not sure using union with single argument is kind of hack.

```
const onSetLoadingAction = union(setLoading);
function* onSetLoading(action: typeof onSetLoadingAction.actions) 
```

Could you please let know if there is a better way to obtain this info from setLoading.

Thank you!

**Comment by cartant** [comment]
You should only need to call `union` when dealing with multiple actions. Use TypeScript's built-in `ReturnType`:

```ts
function* onSetLoading(action: Return type<typeof setLoading>)
```

**Comment by aarjithn** [comment]
Thank you! That worked.
