### ISSUE TITLE
Suggested adding this solution to the NgRx platform.  

### ISSUE THREAD

**Issue by jaufgang** [cartant/ts-action#6]
Just a heads up, I think this package is so great I suggested to the NgRx team that this or a solution based on it be added to the NgRx platform:   https://github.com/ngrx/platform/issues/584

IMHO, this really should be the default way that all or most NgRx users create and use actions.

**Comment by cartant** [comment]
I'm pleased you've found it useful. I'm currently building a DevTools extension for [`rxjs-spy`](https://github.com/cartant/rxjs-spy/) and I'm using ngrx for the panel. With `ts-action` and `@ngrx/entity`, the amount of boilerplate I've been able to avoid has greatly improved my mood.

**Comment by cartant** [comment]
https://github.com/ngrx/platform/blob/24711ca16c58c9d2e4391d012585c4f280fb0c43/modules/store/src/action_creator.ts#L11
