### ISSUE TITLE
I need an es5 package

### ISSUE THREAD

**Issue by JulienBourgain** [cartant/ts-action#9]
I don't know why, but in my project, we can compile your lib on every computer in the openspace (windows or linux) but on our jenkins, the angular cli production build failed on guard.js file.

I have forked your lib to provide an es5 version. It works ! https://www.npmjs.com/package/ts-action-es5

But i don't want to fork your lib :(
Can you provide multiple package compilation (es5 and es2015 and umd) on NPM ?

I don't have access to youtube at works, but an ng-conf video talks about multiple compilation target for libraries if you want some informations.
One core maintener of angular cli demonstrate that multi targets build with => https://github.com/filipesilva/angular-quickstart-lib

And ng-packger can do some of these magic of you => https://www.npmjs.com/package/ng-packagr

Angular-cli v1.6.0 to 1.6.6
Angular 4.4.6
Typescript 2.6.2
Yarn 0.24.2 to 1.3.2
Node 8.9.0
ts-action 3.2.2

and the stacktrace
[ERROR] ERROR in main.2079216f4592de770057.bundle.js from UglifyJs
[ERROR] Unexpected token: operator (>) [/var/lib/jenkins/workspace/SIX-FT-webapp-build-no-master/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js??ref--4-0!/var/lib/jenkins/workspace/SIX-FT-webapp-build-no-master/node_modules/ts-action/guard.js:5,0][main.2079216f4592de770057.bundle.js:110682,21]

**Comment by JulienBourgain** [comment]
This is why the angular package format >=4 need to build an es5 build, an es2015 build and an umd build.

You can provide multiple package entry point in your bundled package.json like : 
"main": "./bundles/quickstart-lib.umd.js",
"module": "./quickstart-lib.es5.js",
"es2015": "./quickstart-lib.js",

and angular-cli understands that.

You can see a way to do that with this build file => https://github.com/filipesilva/angular-quickstart-lib/blob/master/build.js

**Comment by cartant** [comment]
I understand that is the intention, but I would like to confirm that it works before merging it. Regardless, it will still be a major version bump as the package does not have to be used with Angular.

**Comment by cartant** [comment]
I've tested this and I've published 4.0.0 which includes CommonJS, ES5 and ES2015 files.
